name = "brasil-varejo-api"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = [ "nodejs_compat" ]

[[kv_namespaces]]
binding = "CARRINHO"
id = "1ceee220165e4b6cabc16a6928c08bcc"