name = "brasil-varejo-api"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = [ "nodejs_compat" ]

[[kv_namespaces]]
binding = "CARRINHO"
id = "1ceee220165e4b6cabc16a6928c08bcc"

[vars]
SANITY_PROJECT_ID = "o4upb251"
SANITY_DATASET = "production"
# OBS: Apaguei o SANITY_TOKEN daqui. 
# As outras chaves (MP e RESEND) podem ficar por enquanto para facilitar, 
# mas o ideal é mover para secrets depois também.

MP_ACCESS_TOKEN = "APP_USR-7169422151606991-010921-65c4fa0e492f0ea093b55dadcdc8521a-3116067230"
RESEND_API_KEY = "re_Yr1tfCgq_NigfG8QTmmuywWVtnWvJLN8C"